<h1>List Names</h1>
<table id="list-names">
	<thead>
		<tr>
			<th>Title</th>
			<th>First Name</th>
			<th>Middle Name</th>
			<th>Last Name</th>
		</tr>
	</thead>
</table>
<?php
$this->headLink()
    ->prependStylesheet('https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css');
$this->inlineScript()
    ->prependFile('https://code.jquery.com/jquery-3.5.1.min.js')
    ->prependFile('https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js');
?>
<script>
$(document).ready(function() {
    $('#list-names').DataTable( {
		'ajax': '/api/names'
    });
} );
</script>
