<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
<h1>List Names</h1>
<table id="list-names">
	<thead>
		<tr>
			<th>Title</th>
			<th>First Name</th>
			<th>Middle Name</th>
			<th>Last Name</th>
		</tr>
	</thead>
</table>
<script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script>
$(document).ready(function() {
    $('#list-names').DataTable(
		"ajax": '/api/names'
    );
} );
</script>
