<?php $this->headTitle('Home'); ?>

<div class="jumbotron">
    <h1>Welcome to <span class="mezzio-green">The Linux for PHP <i>IpWhat</i> Demo Project</span></h1>
    <p>
        This demo app is based upon the 
        <a href="https://github.com/mezzio/mezzio-skeleton" target="_blank">Mezzio skeleton application</a>.
        This skeleton can serve as a simple starting point for you to begin building your application.
        It's designed to demonstrate uploading an application to the <a href="">Linux for PHP Cloud</a>
        using <a href="https://github.com/linuxforphp/linuxforcomposer">Linux for Composer</a>, based upon the acclaimed <a href="http://linuxforphp.net/">Linux for PHP</a> Docker image.
		We would like to thank the <a href="https://getlaminas.org/">Laminas Project</a> for the overall framework used in this demo.
		We would also like to give credit to the <a href="https://about.ip2c.org/#about">IP2C project</a> for providing a simple API that produces
		country info from an IP address.
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>
            <a href="https://linuxforphp.com/" target="_blank">
                <i class="fa fa-bolt"></i> Cloud Services
            </a>
        </h2>
        <p>
		Publishing a website to a cloud infrastructure for the first time can be a daunting task for both a non-
		technical person and a web developer, especially when the web application is to be containerized with
		Docker. Moreover, many current cloud offerings are prohibitively complicated when it comes to
		calculating monthly costs and configuring future web applications.
		Linux for PHP Cloud Services simplifies this process by making its cloud infrastructure easily accessible
		to content publishers, offering a one-click publication process. Further, billing is extremely transparent,
		taking the form of a fixed monthly cost. No more need for complicated calculations or having to hire
		consultants with a Master’s Degree in Computer Science when trying to figure out cloud terminology!
        </p>
    </div>

    <div class="col-md-4">
        <h2>
            <a href="https://linuxforphp.net/" target="_blank">
                <i class="fa fa-image"></i> Linux for PHP
            </a>
        </h2>
        <p>
		The Linux for PHP (LfPHP) Docker image combines the best of two worlds.
		<ul>
		<li>Based upon a custom created a custom, streamlined version of Linux known as <i>ASCLinux</i></li>
		<li>Includes a custom compiled version of PHP with the latest stable core and extensions</li>
		</ul>
		LfPHP is also a full <i>LAMPPP</i> stack that includes:
		<ul>
		<li>Linux </li>
		<li>Apache and nginx</li>
		<li>MariaDB, PostgreSQL and also MongoDB!</li>
		<li>not only <b>PHP</b>, but <i>Python</i> , <i>Perl</i> and even <i>Ruby</i></li>
		</ul>
        </p>
    </div>

    <div class="col-md-4">
        <h2>
            <a href="https://php-cl.com/" target="_blank">
                <i class="fa fa-graduation-cap"></i> Continuous Learning
            </a>
        </h2>
        <p>
		FCF Continuous Learning has on board a staff of instructors who are highly acclaimed in the 
		PHP community and experts in their respective fields.  FCF Continuous Learning has an integrated 
		​<i>Learning Management System</i>​ that fosters not only a platform upon which you can communicate 
		with your instructor, but also allows you to develop relationship with other students. 

		Additionally, FCF Continuous Learning offers you your own cloud based container,
		built upon the top-rated​ ​<i>Linux for PHP Cloud Services</i>​ platform, that is yours to 
		to use for the duration of the class. This greatly reduces the initial effort and stress inherent
		in online learning platforms by eliminating the need for to install and configure software. 
		You simply click on a link to spin up your new course work space and allowing you to begin
		developing lab code right away.
        </p>
    </div>
</div>

