<?php $this->headTitle('Home'); ?>

<div class="jumbotron">
    <h1>Welcome to <span class="mezzio-green">The Linux for PHP <i>IpWhat</i> Demo Project</span></h1>
    <p>
        This demo app is based upon the 
        <a href="https://github.com/mezzio/mezzio-skeleton" target="_blank">mezzio skeleton application</a>.
        This skeleton can serve as a simple starting point for you to begin building your application.
        It's designed to demonstrate uploading an application to the <a href="">Linux for PHP Cloud</a>
        using <a href="https://github.com/linuxforphp/linuxforcomposer">Linux for Composer</a>, based upon the acclaimed <a href="http://linuxforphp.net/">Linux for PHP</a> Docker image.
		We would like to thank the <a href="https://getlaminas.org/">Laminas Project</a> for the overall framework used in this demo.
		We would also like to give credit to the <a href="https://about.ip2c.org/#about">IP2C project</a> for providing a simple API that produces
		country info from an IP address.  Please donate!
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>
            <a href="https://linuxforphp.com/" target="_blank">
                <i class="fa fa-bolt"></i> Cloud Services
            </a>
        </h2>
        <p>
		Publishing a website to a cloud infrastructure for the first time can be a daunting task for both a non-
		technical person and a web developer, especially when the web application is to be containerized with
		Docker. Moreover, many current cloud offerings are prohibitively complicated when it comes to
		calculating monthly costs and configuring future web applications.
		Linux for PHP Cloud Services simplifies this process by making its cloud infrastructure easily accessible
		to content publishers, offering a one-click publication process. Further, billing is extremely transparent,
		taking the form of a fixed monthly cost. No more need for complicated calculations or having to hire
		consultants with a Master’s Degree in Computer Science when trying to figure out cloud terminology!
        </p>
    </div>

    <div class="col-md-4">
        <h2>
            <a href="https://linuxforphp.net/" target="_blank">
                <i class="fa fa-image"></i> Linux for PHP
            </a>
        </h2>
        <p>
		The Linux for PHP (LfPHP) Docker image combines the best of two worlds: Linux and PHP
		<ul>
		<li>Based upon a custom created _lean and mean_ version of Linux known as <i>ASCLinux</i></li>
		<li>Includes a custom compiled version of PHP with the latest stable core and extensions</li>
		</ul>
		LfPHP is also a full _LAMPPP_ stack that includes ... :
		<ul>
		<li>... Linux </li>
		<li>... Apache 2.4 and nginx</li>
		<li>... MariaDB, PostgreSQL and also MongoDB!</li>
		<li>... not only PHP, but _Python_ , _Perl_ and even _Ruby_</li>
		</ul>
        </p>
    </div>

    <div class="col-md-4">
        <h2>
            <a href="https://php-cl.com/" target="_blank">
                <i class="fa fa-graduation-cap"></i> Continuous Learning
            </a>
        </h2>
        <p>
		In today’s economy, the costs associated with developing new courses is high. FCF
		Continuous Learning brings to the table <i>FCF CourseBuilder</i>​, a combined course development
		and delivery platform that automates the development process to such an extent whereby
		new content can be developed quickly and made available for immediate delivery.
		
		FCF Continuous Learning has an integrated ​<i>Learning Management System</i>​ that fosters
		relationships with students. Finally, FCF Continuous Learning has on board a staff of
		instructors who are highly acclaimed in the PHP community and experts in their respective
		fields.

		Additionally, FCF Continuous Learning offers each student their own cloud based container,
		built upon the top-rated​ ​<i>Linux for PHP</i>​ platform. Each student is given their own container
		to use for the duration of the class. This greatly reduced the initial effort and stress for
		students by eliminating the need for them to install and configure software. Students click
		a link to spin up their new course work space and can begin working.
        </p>
    </div>
</div>

